Repository UMC-CodePlay/CodePlay-BE, pull requests merged in 2025-01, with the labels that each got.

#6 [Docs] issue, pr template 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/etc-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#7 Template edit
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/etc-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#8 Build ci
  .github/hooks/pre-commit
  .github/workflows/build-test.yml
  HELP.md
  build.gradle
  env/local.env
  src/main/java/umc/codeplay/CodeplayApplication.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/umc/codeplay/CodeplayApplicationTests.java
  src/test/resources/application-test.yml
Labels: Test

#17 #15 ci test
  .github/workflows/build-test.yml
  build.gradle
  src/main/java/umc/codeplay/CodeplayApplication.java
  src/test/java/umc/codeplay/CodeplayApplicationTests.java
Labels: Test

#19 스웨거 세팅 진행
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/etc-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  build.gradle
  src/main/java/umc/codeplay/config/SwaggerConfig.java
Labels: Feat

#21 [Feat] 스프링 시큐리티 설정(#13)
  build.gradle
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/controller/MemberViewController.java
Labels: Feat

#22 기본 회원가입 설정(#12)
  build.gradle
  src/main/java/umc/codeplay/controller/MemberViewController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/repository/MemberRepository.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: Feat

#24 [Feat] JWT + Spring Security 로그인/회원가입 구현
  build.gradle
  src/main/java/umc/codeplay/CodeplayApplication.java
  src/main/java/umc/codeplay/apiPayLoad/ApiResponse.java
  src/main/java/umc/codeplay/apiPayLoad/code/BaseCode.java
  src/main/java/umc/codeplay/apiPayLoad/code/BaseErrorCode.java
  src/main/java/umc/codeplay/apiPayLoad/code/ErrorReasonDTO.java
  src/main/java/umc/codeplay/apiPayLoad/code/ReasonDTO.java
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/umc/codeplay/apiPayLoad/exception/ExceptionAdvice.java
  src/main/java/umc/codeplay/apiPayLoad/exception/GeneralException.java
  src/main/java/umc/codeplay/apiPayLoad/exception/handler/GeneralHandler.java
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/config/SwaggerConfig.java
  src/main/java/umc/codeplay/config/security/CustomUserDetailsService.java
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/controller/MemberViewController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/enums/Role.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/codeplay/jwt/JwtUtil.java
  src/main/java/umc/codeplay/repository/MemberRepository.java
  src/main/java/umc/codeplay/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/umc/codeplay/CodeplayApplicationTests.java
Labels: Feat, !BREAKING CHANGE

#27 Docker compose
  README.md
  build.gradle
  env/local.env
  mysql/.env
  mysql/docker-compose.yml
  src/main/resources/application.yml
Labels: Chore

#29 환경변수 .env로 옮김
  env/local.env
  src/main/java/umc/codeplay/apiPayLoad/ApiResponse.java
  src/main/java/umc/codeplay/apiPayLoad/code/ErrorReasonDTO.java
  src/main/java/umc/codeplay/apiPayLoad/code/ReasonDTO.java
  src/main/java/umc/codeplay/jwt/JwtUtil.java
Labels: Style, Refactor

#51 [Chore] 배포 테스트
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/etc-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/hooks/pre-commit
  .github/workflows/build-test.yml
  .github/workflows/docker-deploy.yml
  .gitignore
  HELP.md
  README.md
  build.gradle
  docker/deploy/docker-compose.yml
  docker/local/docker-compose.yml
  env/local-db.env
  env/local-spring.env
  env/prod-db.env
  env/prod-spring.env
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/codeplay/CodeplayApplication.java
  src/main/java/umc/codeplay/apiPayLoad/ApiResponse.java
  src/main/java/umc/codeplay/apiPayLoad/code/BaseCode.java
  src/main/java/umc/codeplay/apiPayLoad/code/BaseErrorCode.java
  src/main/java/umc/codeplay/apiPayLoad/code/ErrorReasonDTO.java
  src/main/java/umc/codeplay/apiPayLoad/code/ReasonDTO.java
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/umc/codeplay/apiPayLoad/exception/ExceptionAdvice.java
  src/main/java/umc/codeplay/apiPayLoad/exception/GeneralException.java
  src/main/java/umc/codeplay/apiPayLoad/exception/handler/GeneralHandler.java
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/config/SwaggerConfig.java
  src/main/java/umc/codeplay/config/security/CustomUserDetailsService.java
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/enums/Role.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/codeplay/jwt/JwtUtil.java
  src/main/java/umc/codeplay/repository/MemberRepository.java
  src/main/java/umc/codeplay/service/MemberService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/umc/codeplay/CodeplayApplicationTests.java
  src/test/resources/application-test.yml
Labels: Test, Chore

#53 [Chore] Docker setting
  README.md
  docker/deploy/deploy.sh
  docker/deploy/docker-compose.yml
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/controller/HealthCheck.java
Labels: Test, Chore

#55 [Chore] github action 배포 스크립트 변경
  .github/workflows/docker-deploy.yml
Labels: Test, Chore

#57 [Fix] Health check시 responseEntity 사용
  src/main/java/umc/codeplay/controller/HealthCheck.java
Labels: FIx

#59 [Feat] client 요청시 cors 전체 허용으로 설정
  src/main/java/umc/codeplay/config/WebConfig.java
Labels: Feat

#62 [Test] merge commit @ pr
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/etc-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/hooks/pre-commit
  .github/workflows/build-test.yml
  .github/workflows/docker-deploy.yml
  .gitignore
  HELP.md
  README.md
  build.gradle
  docker/deploy/deploy.sh
  docker/deploy/docker-compose.yml
  docker/local/docker-compose.yml
  env/local-db.env
  env/local-spring.env
  env/prod-db.env
  env/prod-spring.env
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/codeplay/CodeplayApplication.java
  src/main/java/umc/codeplay/apiPayLoad/ApiResponse.java
  src/main/java/umc/codeplay/apiPayLoad/code/BaseCode.java
  src/main/java/umc/codeplay/apiPayLoad/code/BaseErrorCode.java
  src/main/java/umc/codeplay/apiPayLoad/code/ErrorReasonDTO.java
  src/main/java/umc/codeplay/apiPayLoad/code/ReasonDTO.java
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/umc/codeplay/apiPayLoad/exception/ExceptionAdvice.java
  src/main/java/umc/codeplay/apiPayLoad/exception/GeneralException.java
  src/main/java/umc/codeplay/apiPayLoad/exception/handler/GeneralHandler.java
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/config/SwaggerConfig.java
  src/main/java/umc/codeplay/config/WebConfig.java
  src/main/java/umc/codeplay/config/security/CustomUserDetailsService.java
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/controller/HealthCheck.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/enums/Role.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/codeplay/jwt/JwtUtil.java
  src/main/java/umc/codeplay/repository/MemberRepository.java
  src/main/java/umc/codeplay/service/MemberService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/umc/codeplay/CodeplayApplicationTests.java
  src/test/resources/application-test.yml
Labels: Test

#64 [Fix] Update build-test.yml
  .github/workflows/build-test.yml
Labels: FIx

#65 [Fix] Update build-test.yml
  .github/workflows/build-test.yml
Labels: FIx

#67 [Fix] Update build-test.yml
  .github/workflows/build-test.yml
Labels: FIx

#63 [Feat] S3 setting 및 파일 업로드 로직
  .gitignore
  build.gradle
  docker/deploy/deploy.sh
  docker/deploy/docker-compose.yml
  env/local-db.env
  env/local-spring.env
  env/prod-db.env
  env/prod-spring.env
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/config/AWSConfig.java
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/controller/HealthCheck.java
  src/main/java/umc/codeplay/jwt/JwtUtil.java
  src/main/java/umc/codeplay/service/S3Service.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: Feat

#71 [Feat] Create Domain Table
  src/main/java/umc/codeplay/domain/Harmony.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/domain/Track.java
  src/main/java/umc/codeplay/domain/common/BaseEntity.java
  src/main/java/umc/codeplay/domain/mapping/MusicLike.java
Labels: Feat

#74 [Feat] 즐겨찾기 추가/삭제 (#36)
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/controller/LikeController.java
  src/main/java/umc/codeplay/converter/MusicLikeConverter.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/dto/LikeRequestDTO.java
  src/main/java/umc/codeplay/dto/LikeResponseDTO.java
  src/main/java/umc/codeplay/repository/MusicLikeRepository.java
  src/main/java/umc/codeplay/repository/MusicRepository.java
  src/main/java/umc/codeplay/service/LikeService.java
Labels: Feat

#78 [Refactor] 환경변수 추가에 따른 Update build-test.yml
  .github/workflows/build-test.yml
Labels: Refactor, Chore

#79 [Fix] 배포 환경에 환경변수 추가
  src/main/resources/application-prod.yml
Labels: FIx

#81 [Test] Update build-test.yml
  .github/workflows/build-test.yml
Labels: Test

#82 [Style] 간격 및 필요없는 코드 제거
  src/main/java/umc/codeplay/controller/HealthCheck.java
  src/main/java/umc/codeplay/dto/LikeRequestDTO.java
  src/main/java/umc/codeplay/dto/LikeResponseDTO.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
Labels: Style

#83 [Fix] baseEntity 자동 반영되도록 수정
  src/main/java/umc/codeplay/CodeplayApplication.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/domain/common/BaseEntity.java
Labels: FIx

#84 [Refactor] S3 presignedurl로 변경
  .github/workflows/build-test.yml
  build.gradle
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/config/AWSConfig.java
  src/main/java/umc/codeplay/controller/FileController.java
  src/main/java/umc/codeplay/dto/FileResponseDTO.java
  src/main/java/umc/codeplay/service/FileService.java
  src/main/java/umc/codeplay/service/S3Service.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Refactor

#86 [Test] 필요없는 부분 제거 테스트
  src/main/java/umc/codeplay/config/AWSConfig.java
Labels: Test

#87 [Chore] 2025/01/26 배포 2차
  .github/workflows/build-test.yml
  .gitignore
  build.gradle
  docker/deploy/deploy.sh
  docker/deploy/docker-compose.yml
  env/local-db.env
  env/local-spring.env
  env/prod-db.env
  env/prod-spring.env
  src/main/java/umc/codeplay/CodeplayApplication.java
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/config/AWSConfig.java
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/config/properties/BaseOAuthProperties.java
  src/main/java/umc/codeplay/config/properties/GoogleOAuthProperties.java
  src/main/java/umc/codeplay/config/properties/KakaoOAuthProperties.java
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/controller/FileController.java
  src/main/java/umc/codeplay/controller/HealthCheck.java
  src/main/java/umc/codeplay/controller/LikeController.java
  src/main/java/umc/codeplay/controller/OAuthController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/converter/MusicLikeConverter.java
  src/main/java/umc/codeplay/domain/Harmony.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/domain/Track.java
  src/main/java/umc/codeplay/domain/common/BaseEntity.java
  src/main/java/umc/codeplay/domain/enums/SocialStatus.java
  src/main/java/umc/codeplay/domain/mapping/MusicLike.java
  src/main/java/umc/codeplay/dto/FileResponseDTO.java
  src/main/java/umc/codeplay/dto/LikeRequestDTO.java
  src/main/java/umc/codeplay/dto/LikeResponseDTO.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/jwt/JwtUtil.java
  src/main/java/umc/codeplay/repository/MusicLikeRepository.java
  src/main/java/umc/codeplay/repository/MusicRepository.java
  src/main/java/umc/codeplay/service/FileService.java
  src/main/java/umc/codeplay/service/LikeService.java
  src/main/java/umc/codeplay/service/MemberService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: Chore

#89 [Refactor] 파일 다운로드 로직 업데이트
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/config/SwaggerConfig.java
  src/main/java/umc/codeplay/controller/FileController.java
  src/main/java/umc/codeplay/service/FileService.java
Labels: Refactor

#93 [Feat] 이메일인증 api 생성 (#70)
  build.gradle
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/dto/EmailCodeDTO.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/service/EmailService.java
  src/main/resources/application.yml
Labels: Feat

#94 [Feat]UpdateMemberInfo(#32)
  src/main/java/umc/codeplay/config/security/CustomUserDetails.java
  src/main/java/umc/codeplay/config/security/CustomUserDetailsService.java
  src/main/java/umc/codeplay/controller/MemberController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/enums/Role.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/codeplay/service/MemberService.java
  src/main/resources/application.yml
Labels: Feat
