Repository UMC-CodePlay/CodePlay-BE, pull requests merged in 2025-02, with the labels that each got.

#98 [Fix]좋아요추가수정#97
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/converter/MusicLikeConverter.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/dto/LikeResponseDTO.java
  src/main/java/umc/codeplay/repository/MusicLikeRepository.java
  src/main/java/umc/codeplay/service/LikeService.java
Labels: FIx

#100 [chore] swagger hidden
  src/main/java/umc/codeplay/controller/OAuthController.java
Labels: Chore

#102 [Refactor] fileUpload시 image일 경우 분기
  src/main/java/umc/codeplay/controller/FileController.java
  src/main/java/umc/codeplay/domain/enums/FileType.java
  src/main/java/umc/codeplay/dto/FileResponseDTO.java
  src/main/java/umc/codeplay/service/FileService.java
Labels: Feat, Refactor

#105 Fix/modify member update
  src/main/java/umc/codeplay/controller/MemberController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: FIx

#106 Feat/mypage per taps/#34
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/controller/MemberController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Harmony.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/repository/HarmonyRepository.java
  src/main/java/umc/codeplay/service/LikeService.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: Feat

#108 Feat/delete namein member/#107
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/controller/OAuthController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/codeplay/jwt/JwtUtil.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: FIx

#123 feat/MypageSearch/#33
  src/main/java/umc/codeplay/controller/MemberController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/repository/HarmonyRepository.java
  src/main/java/umc/codeplay/repository/MusicRepository.java
  src/main/java/umc/codeplay/repository/TrackRepository.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: Feat

#124 [Feat] 파이썬 로컬 서버 결과 db에 반영
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/controller/FileController.java
  src/main/java/umc/codeplay/controller/ModelResultController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Harmony.java
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/domain/Remix.java
  src/main/java/umc/codeplay/domain/Task.java
  src/main/java/umc/codeplay/domain/Track.java
  src/main/java/umc/codeplay/domain/enums/JobType.java
  src/main/java/umc/codeplay/domain/enums/ProcessStatus.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/dto/ModelRequestDTO.java
  src/main/java/umc/codeplay/dto/ModelResponseDTO.java
  src/main/java/umc/codeplay/repository/HarmonyRepository.java
  src/main/java/umc/codeplay/repository/RemixRepository.java
  src/main/java/umc/codeplay/repository/TaskRepository.java
  src/main/java/umc/codeplay/repository/TrackRepository.java
  src/main/java/umc/codeplay/service/ModelService.java
Labels: Feat, !BREAKING CHANGE

#126 [Docs] Update README.md
  README.md
Labels: Docs

#130 [Feat] 특정 기간 후 입력/결과 데이터 자동 삭제
  docker/local/deleteEvent.sql
  src/main/java/umc/codeplay/domain/Member.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/domain/Remix.java
  src/main/java/umc/codeplay/repository/RemixRepository.java
Labels: Feat

#132 [Fix] 잘못된 enum명 수정
  src/main/java/umc/codeplay/domain/Task.java
  src/main/java/umc/codeplay/domain/enums/JobType.java
Labels: FIx

#134 Timezone
  build.gradle
  docker/deploy/deploy.sh
  docker/deploy/docker-compose.yml
Labels: Chore

#138 [Feat]비밀번호 재설정 #114
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/controller/LikeController.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/service/EmailService.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: Feat

#140 [feat] 작업 요청 - SQS 메세지 생성 / 작업 진행 상황 조회 / 작업 진행 상황 업데이트(파이썬)
  .github/workflows/build-test.yml
  build.gradle
  src/main/java/umc/codeplay/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/codeplay/config/SecurityConfig.java
  src/main/java/umc/codeplay/controller/ModelController.java
  src/main/java/umc/codeplay/controller/TaskController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/domain/Remix.java
  src/main/java/umc/codeplay/domain/Task.java
  src/main/java/umc/codeplay/domain/enums/ProcessStatus.java
  src/main/java/umc/codeplay/dto/MemberRequestDTO.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/dto/ModelRequestDTO.java
  src/main/java/umc/codeplay/dto/ModelResponseDTO.java
  src/main/java/umc/codeplay/dto/SQSMessageDTO.java
  src/main/java/umc/codeplay/service/ModelService.java
  src/main/java/umc/codeplay/service/MusicService.java
  src/main/java/umc/codeplay/service/TaskService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Feat, !BREAKING CHANGE

#152 로그인시 프로필 이미지 return 추가
  src/main/java/umc/codeplay/controller/AuthController.java
  src/main/java/umc/codeplay/converter/MemberConverter.java
  src/main/java/umc/codeplay/dto/MemberResponseDTO.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: Feat

#156 File name
  src/main/java/umc/codeplay/controller/FileController.java
  src/main/java/umc/codeplay/controller/TaskController.java
  src/main/java/umc/codeplay/domain/Harmony.java
  src/main/java/umc/codeplay/domain/Music.java
  src/main/java/umc/codeplay/domain/Remix.java
  src/main/java/umc/codeplay/domain/Track.java
  src/main/java/umc/codeplay/domain/enums/FileType.java
  src/main/java/umc/codeplay/service/FileService.java
Labels: Refactor

#160 Feat/search with task id/#153
  src/main/java/umc/codeplay/controller/TaskController.java
  src/main/java/umc/codeplay/converter/TaskConverter.java
  src/main/java/umc/codeplay/dto/TaskResponseDTO.java
  src/main/java/umc/codeplay/service/TaskService.java
Labels: Feat

#163 [Feat]비번찾기이메일설정(#155)
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Feat

#164 6.2차 배포
  src/main/java/umc/codeplay/controller/OAuthController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Feat

#173 fix/MypageSearchReturnFix/#169
  src/main/java/umc/codeplay/controller/MemberController.java
  src/main/java/umc/codeplay/repository/MusicRepository.java
  src/main/java/umc/codeplay/service/MemberService.java
Labels: FIx

#175 fix/ParticialSearch/#174
  src/main/java/umc/codeplay/controller/MemberController.java
  src/main/java/umc/codeplay/repository/MusicRepository.java
Labels: FIx
